#!/usr/bin/env node
// Graysmith Labs guard hook for Claude Code.
//
// PreToolUse (Bash): blocks commits not authored as Ramsey, attribution
// trailers, claude/ branches, generated by lines in pull requests, and Google
// test ad unit IDs headed into production code.
// PostToolUse (Edit, Write, MultiEdit): checks store.config.json against App
// Store limits and the no dashes rule, and hands problems back to Claude.
//
// Exit 2 with a message on stderr blocks the call (Pre) or reports back (Post).
// Any internal error exits 0, so a broken hook never stops work.

import { execSync } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';
import { basename } from 'node:path';

const OWNER_NAME = 'Ramsey Graysmith';
const OWNER_EMAIL = 'smith.s.ramsey@gmail.com';
const TEST_PUBLISHER = 'ca-app-pub-3940256099942544';

function block(msg) {
  process.stderr.write(msg.trim() + '\n');
  process.exit(2);
}

function sh(cmd, cwd) {
  try {
    return execSync(cmd, { cwd, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return '';
  }
}

// Prose dash check that ignores URLs and email addresses.
export function proseDashes(text) {
  const stripped = String(text)
    .replace(/https?:\/\/\S+/g, ' ')
    .replace(/\S+@\S+/g, ' ');
  const hits = [];
  for (const line of stripped.split('\n')) {
    if (/[‐-―−]/.test(line) || /(^|[\s(])-(\s|$)|\w-\w/.test(line)) hits.push(line.trim().slice(0, 80));
  }
  return hits;
}

export function lintStoreConfig(json) {
  const problems = [];
  const info = json?.apple?.info || {};
  const LIMITS = { title: 30, subtitle: 30, promoText: 170, description: 4000, releaseNotes: 4000 };
  for (const [locale, l] of Object.entries(info)) {
    for (const [field, max] of Object.entries(LIMITS)) {
      if (typeof l[field] !== 'string') continue;
      if (l[field].length > max) problems.push(`${locale} ${field} is ${l[field].length} characters, limit ${max}`);
      for (const hit of proseDashes(l[field])) problems.push(`${locale} ${field} has a dash: "${hit}"`);
    }
    if (Array.isArray(l.keywords)) {
      const joined = l.keywords.join(',');
      if (joined.length > 100) problems.push(`${locale} keywords are ${joined.length} characters joined, limit 100`);
      const named = `${l.title || ''} ${l.subtitle || ''}`.toLowerCase();
      for (const k of l.keywords) {
        if (!/\s/.test(k.trim()) && named.split(/[^a-z0-9]+/).includes(k.toLowerCase()))
          problems.push(`${locale} keyword "${k}" already appears in the title or subtitle, so it wastes space`);
        if (/^(app|free)$/i.test(k)) problems.push(`${locale} keyword "${k}" is ignored by Apple`);
      }
    }
  }
  return problems;
}

export function checkCommand(cmd, cwd) {
  const isCommit = /\bgit\b[^;&|]*\bcommit\b/.test(cmd);
  const branch = /\bgit\b[^;&|]*\b(checkout\s+-b|switch\s+-c|branch|push)\b[^;&|]*\bclaude\//.test(cmd);
  if (branch) return 'Branch names starting with claude/ are not allowed. Use growth/<topic>.';
  if (/Co-Authored-By|Claude-Session/i.test(cmd))
    return 'Remove the Co-Authored-By and Claude-Session trailers. Commits are Ramsey\'s alone.';
  if (/\bgh\s+pr\s+(create|edit)\b/.test(cmd) && /Generated with|claude\.com\/claude-code|claude\.ai\/code/i.test(cmd))
    return 'Remove the generated by line and Claude links from the pull request body.';
  if (isCommit) {
    const author = /--author[= ]["']?([^"']+)/.exec(cmd);
    if (author && !author[1].includes(OWNER_EMAIL)) return `Commits must be authored as ${OWNER_NAME} <${OWNER_EMAIL}>.`;
    const fileArg = /\s(?:-F|--file)[= ]["']?([^\s"']+)/.exec(cmd);
    if (fileArg && existsSync(fileArg[1]) && /Co-Authored-By|Claude-Session/i.test(readFileSync(fileArg[1], 'utf8')))
      return 'The commit message file has attribution trailers. Remove them.';
    const email = sh('git config user.email', cwd);
    const name = sh('git config user.name', cwd);
    if (email && (email !== OWNER_EMAIL || name !== OWNER_NAME))
      return `Git identity is ${name} <${email}>. Run: git config user.name "${OWNER_NAME}" && git config user.email "${OWNER_EMAIL}"`;
    // Only app code can ship a test ID. Docs, tests and this hook mention it on purpose.
    const CODE = /\.(m?[jt]sx?|json)$/;
    const SKIP = /(^|\/)(\.claude|__tests__|node_modules)\/|\.(test|spec)\./;
    const diff = sh('git diff HEAD -U0 --no-color', cwd);
    const added = [];
    let current = '';
    for (const l of diff.split('\n')) {
      if (l.startsWith('+++ ')) current = l.slice(6);
      else if (l.startsWith('+') && CODE.test(current) && !SKIP.test(current)) added.push(l);
    }
    // New files are not in the diff yet when the command is `git add -A && git commit`.
    for (const f of sh('git ls-files --others --exclude-standard', cwd).split('\n').filter(Boolean)) {
      if (!CODE.test(f) || SKIP.test(f)) continue;
      try {
        added.push(...readFileSync(`${cwd}/${f}`, 'utf8').split('\n').map((l) => '+' + l));
      } catch {}
    }
    const bad = added.filter((l) => l.includes(TEST_PUBLISHER) && !/__DEV__|TestIds|isDev|DEV/.test(l));
    if (bad.length)
      return `A Google test ad unit ID is being added outside a __DEV__ guard:\n${bad.slice(0, 3).join('\n')}\nGate it on __DEV__ or use the live unit ID. Shipping test IDs earns nothing.`;
  }
  return '';
}

async function main() {
  let raw = '';
  for await (const chunk of process.stdin) raw += chunk;
  const input = JSON.parse(raw || '{}');
  const event = input.hook_event_name;
  const tool = input.tool_name;
  const cwd = input.cwd || process.cwd();

  if (event === 'PreToolUse' && tool === 'Bash') {
    const msg = checkCommand(String(input.tool_input?.command || ''), cwd);
    if (msg) block(msg);
  }

  if (event === 'PostToolUse' && /^(Edit|Write|MultiEdit)$/.test(tool)) {
    const file = input.tool_input?.file_path || '';
    if (basename(file) === 'store.config.json' && existsSync(file)) {
      let json;
      try {
        json = JSON.parse(readFileSync(file, 'utf8'));
      } catch (e) {
        block(`store.config.json is not valid JSON: ${e.message}`);
      }
      const problems = lintStoreConfig(json);
      if (problems.length) block(`store.config.json needs fixes before store:push:\n* ${problems.join('\n* ')}`);
    }
  }
  process.exit(0);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch(() => process.exit(0));
}
